use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "0wNWyfqCcBTAs1ZqWssv88lGhbKpdKRD"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  formats:
    - html
    - json

valkey:
  url: redis://valkey:6379/0
